@JWT_A =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhQHRlc3QuY29tIiwiaWF0IjoxNzY3Nzg5MzI2LCJleHAiOjE3Njc3OTI5MjZ9.Xb0BpeC9f7seVXRfGZ21gmo92WrvbdHpMfvFymTFPBk
@NOTE_ID = 1
@JWT_B =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiQHRlc3QuY29tIiwiaWF0IjoxNzY3Nzg5MzcyLCJleHAiOjE3Njc3OTI5NzJ9.7ifNCEXQd3b2nJnXR1HQrukEcgiIePMonGqg7Tv0W6k
### Register User A
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "email": "a@test.com",
  "password": "password"
}

### Login User A
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "a@test.com",
  "password": "password"
}

### Me (User A)
GET http://localhost:8081/me
Authorization: Bearer {{JWT_A}}

### Create note (User A)
POST http://localhost:8081/notes
Authorization: Bearer {{JWT_A}}
Content-Type: text/plain

note from user A

### Register User B
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "email": "b@test.com",
  "password": "password"
}

### Login User B
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "b@test.com",
  "password": "password"
}

### Ownership test
GET http://localhost:8081/notes/{{NOTE_ID}}
Authorization: Bearer {{JWT_A}}

### Update note (User A)
PATCH http://localhost:8081/notes/{{NOTE_ID}}
Authorization: Bearer {{JWT_A}}
Content-Type: text/plain

updated content